steps:
  # Docker build & push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '.'

  # Docker push (deploy前に明示的にpush)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'

  # Cloud Run deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--max-instances=3'
      - '--allow-unauthenticated'
      - '--set-env-vars=^##^CORS_ORIGINS=${_CORS_ORIGINS}##ALLOW_UNAUTHENTICATED=${_ALLOW_UNAUTHENTICATED}'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest'

substitutions:
  _REGION: asia-northeast1
  _REPO_NAME: optimizer
  _IMAGE_NAME: shift-optimizer
  _SERVICE_NAME: shift-optimizer
  _CORS_ORIGINS: 'https://visitcare-shift-optimizer.web.app,https://visitcare-shift-optimizer.firebaseapp.com,http://localhost:3000'
  _ALLOW_UNAUTHENTICATED: 'true'
